### ISSUE TITLE
Cannot import the pandasdb module or Database Class

### ISSUE THREAD

**Issue by zaid-kamil** [shner-elmo/pandas-db#3]
Cannot import the pandasdf module and cannot import the Database class as shown in the documentation
![image](https://user-images.githubusercontent.com/5492621/211296571-8623766d-da42-40ca-8ce7-2551132f2a50.png)

**Comment by shner-elmo** [comment]
What python version do you have?

**Comment by zaid-kamil** [comment]
Python 3.9.13 from anaconda

**Comment by shner-elmo** [comment]
Its missing future imports, I updated the package on PyPi, now it should work.

**Comment by zaid-kamil** [comment]
did you update the package on pypi because, 
`pip install pandasdb2 --upgrade` did nothing and the error still persist. 
`from pandasdb import Database` this is giving the same error
![image](https://user-images.githubusercontent.com/5492621/211487444-d860ea41-b373-4ce0-a016-100f83f56209.png)
Python version
![image](https://user-images.githubusercontent.com/5492621/211487516-0423794a-e4aa-47b1-aede-7bd052e7aab3.png)

**Comment by shner-elmo** [comment]
My bad, there was some other stuff that needed to be moved under `if TYPE_CHECKING:`, now it should work.
Also, I changed the folder name to be the same as the package name, so now you can just do: `from pandasdb2 import Database`.
